using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Doom64_Unofficial_Configuration_Tool
{
    public enum RenderFamily
    {
        [Description("Vulkan")] Vulkan,
        [Description("DirectX 11")] D3D11,
        [Description("OpenGL 3.2")] OpenGL
    }

    public enum KeyboardLayout
    {
        QWERTY_WASD,
        QWERTY_ESDF,
        AZERTY,
    }

    public enum D64MouseWheel
    {
        None,
        [Description("Mouse Wheel Up")] mouse_wheel_up,
        [Description("Mouse Wheel Down")] mouse_wheel_down
    }

    public enum GamepadKeys
    {
        None,
        joy_0,
        joy_1,
        joy_2,
        joy_3,
        joy_4,
        joy_5,
        joy_6,
        joy_7,
        joy_8,
        joy_9,
        joy_10,
        joy_11,
        joy_12,
        joy_13,
        joy_14,
        joy_15,
        joy_16
    }

    public enum D64Keys
    {
        //Modified Keys enum
        Modifiers = -65536,
        None = 0,
        [Description("Left Mouse Button")] mouse_left = 1,
        [Description("Right Mouse Button")] mouse_right = 2,
        cancel = 3,
        [Description("Middle Mouse Button")] mouse_middle = 4,
        [Description("Mouse Button 4")] mouse_misc1 = 5,
        [Description("Mouse Button 5")] mouse_misc2 = 6,
        [Description("Backspace")] backspace = 8,
        [Description("Tab")] tab = 9,
        LineFeed = 10,
        Clear = 12,
        [Description("Enter")] enter = 13,
        [Description("Left Shift")] lshift = 16,
        [Description("Left Ctrl")] lctrl = 17,
        [Description("Left Alt")] lalt = 18,
        [Description("Pause Break")] pause = 19,
        Capital = 20,
        [Description("Caps Lock")] Caps_lock = 20,
        KanaMode = 21,
        HanguelMode = 21,
        HangulMode = 21,
        JunjaMode = 23,
        FinalMode = 24,
        HanjaMode = 25,
        KanjiMode = 25,
        Escape = 27,
        IMEConvert = 28,
        IMENonconvert = 29,
        IMEAccept = 30,
        IMEAceept = 30,
        IMEModeChange = 31,
        Space = 32,
        Prior = 33,
        PageUp = 33,
        PageDown = 34,
        End = 35,
        Home = 36,
        Left = 37,
        Up = 38,
        Right = 39,
        Down = 40,
        Select = 41,
        Print = 42,
        Execute = 43,
        [Description("Print Screen")] Prnscreen = 44,
        Insert = 45,
        Delete = 46,
        Help = 47,
        [Description("0")] D0 = 48,
        [Description("1")] D1 = 49,
        [Description("2")] D2 = 50,
        [Description("3")] D3 = 51,
        [Description("4")] D4 = 52,
        [Description("5")] D5 = 53,
        [Description("6")] D6 = 54,
        [Description("7")] D7 = 55,
        [Description("8")] D8 = 56,
        [Description("9")] D9 = 57,
        A = 65,
        B = 66,
        C = 67,
        D = 68,
        E = 69,
        F = 70,
        G = 71,
        H = 72,
        I = 73,
        J = 74,
        K = 75,
        L = 76,
        M = 77,
        N = 78,
        O = 79,
        P = 80,
        Q = 81,
        R = 82,
        S = 83,
        T = 84,
        U = 85,
        V = 86,
        W = 87,
        X = 88,
        Y = 89,
        Z = 90,

        LWin = 91,
        RWin = 92,
        Apps = 93,
        Sleep = 95,

        [Description("Numpad 0")] kp_0 = 96,
        [Description("Numpad 1")] kp_1 = 97,
        [Description("Numpad 2")] kp_2 = 98,
        [Description("Numpad 3")] kp_3 = 99,
        [Description("Numpad 4")] kp_4 = 100,
        [Description("Numpad 5")] kp_5 = 101,
        [Description("Numpad 6")] kp_6 = 102,
        [Description("Numpad 7")] kp_7 = 103,
        [Description("Numpad 8")] kp_8 = 104,
        [Description("Numpad 9")] kp_9 = 105,

        [Description("Numpad *")] kp_mul = 106,
        [Description("Numpad +")] kp_plus = 107,
        Separator = 108, //?
        [Description("Numpad -")] kp_minus = 109,
        [Description("Numpad .")] kp_period = 110,
        [Description("Numpad /")] kp_divide = 111,

        F1 = 112,
        F2 = 113,
        F3 = 114,
        F4 = 115,
        F5 = 116,
        F6 = 117,
        F7 = 118,
        F8 = 119, 
        F9 = 120,
        F10 = 121,
        F11 = 122,
        F12 = 123,
        F13 = 124,
        F14 = 125,
        F15 = 126,
        F16 = 127,
        F17 = 128,
        F18 = 129,
        F19 = 130,
        F20 = 131,
        F21 = 132,
        F22 = 133,
        F23 = 134,
        F24 = 135,

        [Description("NumLock")] numlock = 144,
        [Description("ScrollLock")] scrlock = 145,
        [Description("Left Shift")] LShiftKey = 160,
        [Description("Right Shift")] rshift = 161,
        [Description("Left Ctrl")] LControlKey = 162,
        [Description("Right Ctrl")] rctrl = 163,

        [Description("Left Alt")] LMenu = 164,
        [Description("Left Alt")] ralt = 165,    
        BrowserBack = 166,
        BrowserForward = 167,
        BrowserRefresh = 168,
        BrowserStop = 169,
        BrowserSearch = 170,
        BrowserFavorites = 171,
        BrowserHome = 172,
        VolumeMute = 173,
        VolumeDown = 174,
        VolumeUp = 175,
        MediaNextTrack = 176,
        MediaPreviousTrack = 177,
        MediaStop = 178,
        MediaPlayPause = 179,
        LaunchMail = 180,
        SelectMedia = 181,
        LaunchApplication1 = 182,
        LaunchApplication2 = 183,

        Semicolon = 186,
        [Description("=")] Equals = 187,
        [Description(",")] Comma = 188,
        [Description("-")] Minus = 189,
        [Description(".")] Period = 190,
        [Description("/")] Slash = 191,
        Tilde = 192,
        [Description("[")] Left_brack = 219,
        [Description("\\")] Backslash = 220,
        [Description("]")] Right_brack = 221,
        [Description("\"")] Quote = 222,
        Oem8 = 223,
        [Description("\\")] OemBackslash = 226,

        ProcessKey = 229,
        Packet = 231,
        Attn = 246,
        Crsel = 247,
        Exsel = 248,
        EraseEof = 249,

        Play = 250,
        Zoom = 251,
        NoName = 252,
        Pa1 = 253,
        OemClear = 254,

        //Some missing
        [Description("Numpad Enter")] kp_enter = 255,

        KeyCode = 65535,
        Shift = 65536,
        Control = 131072,
        Alt = 262144
    }
}
