//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doom64_Unofficial_Configuration_Tool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Doom64_Unofficial_Configuration_Tool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bind tab &quot;automap&quot;
        ///bind enter &quot;*menu_select&quot;
        ///bind escape &quot;menu_activate&quot;
        ///bind space &quot;speed&quot;
        ///bind 1 &quot;weapon 1&quot;
        ///bind 2 &quot;weapon 2&quot;
        ///bind 3 &quot;weapon 3&quot;
        ///bind 4 &quot;weapon 5&quot;
        ///bind 5 &quot;weapon 6&quot;
        ///bind 6 &quot;weapon 7&quot;
        ///bind 7 &quot;weapon 8&quot;
        ///bind 8 &quot;weapon 9&quot;
        ///bind a &quot;strafe_left&quot;
        ///bind s &quot;backward&quot;
        ///bind e &quot;use&quot;
        ///bind w &quot;forward&quot;
        ///bind r &quot;mapzoomin&quot;
        ///bind d &quot;strafe_right&quot;
        ///bind q &quot;mapzoomout&quot;
        ///bind f5 &quot;screenshot&quot;
        ///bind f6 &quot;quicksave&quot;
        ///bind f9 &quot;quickload&quot;
        ///bind delete &quot;menu_delete&quot;
        ///bind caps_lock &quot;+autorun&quot;
        ///bind righ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _default {
            get {
                return ResourceManager.GetString("_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
